### ISSUE TITLE
Allow configuration of hardware address (mac)

### ISSUE THREAD

**Issue by mafredri** [stcz/initramfs-tools-network-hook#8]
I would like to be able to configure the hardware address for `bond0` to ensure that both initramfs and systemd receive the same IP via DHCP.

I've locally implemented this via the following change:

```patch
diff --git etc/initramfs-tools/scripts/local-top/bond etc/initramfs-tools/scripts/local-top/bond
index f7377fb..2f63767 100755
--- etc/initramfs-tools/scripts/local-top/bond
+++ etc/initramfs-tools/scripts/local-top/bond
@@ -25,11 +25,15 @@ modprobe bonding $BOND_MODE
 for BOND_IFACE in ${BOND:-*}; do
     BOND_DEVICE=$(echo $BOND_IFACE | cut -d":" -f1)
     BOND_SLAVES=$(echo $BOND_IFACE | cut -d":" -f2 | sed "s/,/ /g")
+    BOND_ADDR=$(echo $BOND_IFACE | cut -d":" -f3-)
     log_begin_msg "Bringing up $BOND_DEVICE"
     ip link add $BOND_DEVICE type bond
     for BOND_SLAVE in $BOND_SLAVES; do
         ip link set $BOND_SLAVE master bond0
     done
+    if [ -n "$BOND_ADDR" ]; then
+        ip link set $BOND_DEVICE address $BOND_ADDR
+    fi
     log_end_msg
 done
```

This can then be configured via `BOND`, e.g. `BOND="bond0:enp9s0,enp8s0:aa:bb:cc:dd:ee:ff"`.

A limitation to this approach is that it won't allow adding future configuration options (due to the `:` separator).

Thoughts, should I continue work on this? Perhaps move it into a new configuration option like `BOND_ADDRESS=bond0:...` (which has makes the parsing less than ideal) or `BOND_ADDRESS_bond0=...`?

**Comment by stcz** [comment]
Thank you for your work.
For me this looks like a nice feature.  But the configuration doesn't look that pretty.

I would prefer to use a format like `BOND="bond0:enp9s0,enp8s0:aa-bb-cc-dd-ee-ff"`

From this follows: 
`BOND_ADDR=$(echo $BOND_IFACE | cut -d":" -f3 | sed "s/-/:/g")`

What do you think about this?
